export const TestIds = {
  app: {
    root: 'app-root',
    totalBalanceXnoDropdown: 'total-balance-xno-dropdown',
    totalBalanceFiatDropdown: 'total-balance-fiat-dropdown',
    totalBalanceXnoCard: 'total-balance-xno-card',
    totalBalanceFiatCard: 'total-balance-fiat-card',
  },
  welcome: {
    pageRoot: 'welcome-page-root',
    createWalletButton: 'welcome-create-wallet-button',
    importWalletButton: 'welcome-import-wallet-button',
  },
  send: {
    pageRoot: 'send-page-root',
    addressInput: 'send-address-input',
    amountInput: 'send-amount-input',
    sendButton: 'send-send-button',
  },
  transfer: {
    toAccountInput: 'transfer-to-account-input',
    amountInput: 'transfer-amount-input',
    transferButton: 'transfer-transfer-button',
  },
  receive: {
    pageRoot: 'receive-page-root',
    addressValue: 'receive-address-value',
    receiveAllButton: 'receive-receive-all-button',
    createNanoNymButton: 'receive-create-nanonym-button',
    nanoNymRow: 'receive-nanonym-row',
    nanoNymRowDetailsButton: 'receive-nanonym-row-details-button',
  },
  addressBook: {
    pageRoot: 'address-book-page-root',
    addContactButton: 'address-book-add-contact-button',
    importAddressBookButton: 'address-book-import-button',
    addressBookRow: 'address-book-row',
    addressBookRowEditButton: 'address-book-row-edit-button',
    addressBookRowDeleteButton: 'address-book-row-delete-button',
  },
  representatives: {
    pageRoot: 'representatives-page-root',
    representativeRow: 'representatives-row',
    representativeRowDetailsButton: 'representatives-row-details-button',
    changeRepresentativeButton: 'representatives-change-representative-button',
    manageRepresentativesButton: 'representatives-manage-representatives-button',
  },
  appSettings: {
    pageRoot: 'app-settings-page-root',
    saveSettingsButton: 'app-settings-save-settings-button',
  },
  manageWallet: {
    pageRoot: 'manage-wallet-page-root',
    changePasswordButton: 'manage-wallet-change-password-button',
    backupWalletButton: 'manage-wallet-backup-wallet-button',
    logoutWalletButton: 'manage-wallet-logout-wallet-button',
    resetWalletButton: 'manage-wallet-reset-wallet-button',
  },
  accounts: {
    pageRoot: 'accounts-page-root',
    createAccountButton: 'accounts-create-account-button',
    importAccountButton: 'accounts-import-account-button',
    accountRow: 'accounts-row',
    accountRowDetailsButton: 'accounts-row-details-button',
    copyAccountIdButton: 'copy-account-id-button',
  },
  walletWidget: {
    unlockButton: 'wallet-widget-unlock-button',
    cancelButton: 'wallet-widget-cancel-button',
  },
  keyGenerator: {
    generateKeypairButton: 'keygenerator-generate-keypair-button',
  },
  multisig: {
    generateMultisigButton: 'multisig-generate-multisig-button',
    resetButton: 'multisig-reset-button',
    createBlockButton: 'multisig-create-block-button',
    signButton: 'multisig-sign-button',
  },
  qrModal: {
    closeButton: 'qr-modal-close-button',
  },
  remoteSigning: {
    createButton: 'remote-signing-create-button',
    signButton: 'remote-signing-sign-button',
    processButton: 'remote-signing-process-button',
  },
  sign: {
    copySigningLinkButton: 'sign-copy-signing-link-button',
    resetMultisigButton: 'sign-reset-multisig-button',
    accountDetailViewButton: 'sign-account-detail-view-button',
    cancelButton: 'sign-cancel-button',
    confirmAndSignButton: 'sign-confirm-and-sign-button',
    signedModalCloseButton: 'sign-signed-modal-close-button',
    outputDataQrModalCloseButton: 'sign-output-data-qr-modal-close-button',
  },
  transactionDetails: {
    copyFromAccountIdButton: 'copy-from-account-id-button',
    copyToAccountIdButton: 'copy-to-account-id-button',
    copyHashIdButton: 'copy-hash-id-button',
    copyPreviousHashButton: 'copy-previous-hash-button',
    copySuccessorHashButton: 'copy-successor-hash-button',
    copySourceHashButton: 'copy-source-hash-button',
    copyWorkButton: 'copy-work-button',
    copySignatureButton: 'copy-signature-button',
  },
} as const;
