const fs = require('fs');
const { execSync } = require('child_process');
const brandingProfiles = require('../branding.json');

const brandingProfile = process.env.FEATURE_NANONYMS === 'true' ? 'nanonyms' : 'naultcore';
const branding = brandingProfiles[brandingProfile];
if (!branding) {
  throw new Error(`Missing branding profile: ${brandingProfile}`);
}
for (const field of ['applicationName', 'loadingText', 'githubUrl', 'attribution']) {
  if (typeof branding[field] !== 'string') {
    throw new Error(`Branding profile ${brandingProfile} is missing string field: ${field}`);
  }
}

// Get the git hash or tag
let version = execSync('git describe --tags --always').toString().trim();

// Check for uncommitted changes to tracked files
// --no-ext-diff: don't use external diff tools
// --quiet: exit with code 1 if there are changes
// This only checks tracked files (ignores untracked)
try {
  execSync('git diff --no-ext-diff --quiet', { stdio: 'ignore' });
  // No changes in working directory
} catch (error) {
  // There are uncommitted changes to tracked files
  version += '-wip';
}

// Also check for staged but uncommitted changes
try {
  execSync('git diff --no-ext-diff --cached --quiet', { stdio: 'ignore' });
  // No staged changes
} catch (error) {
  // There are staged changes
  if (!version.endsWith('-wip')) {
    version += '-wip';
  }
}

const content = `// This file is automatically generated by generate-version.js
export const version = '${version}';
`;

fs.writeFileSync('src/environments/version.ts', content);
const brandingContent = `// This file is automatically generated by generate-version.js
export const branding = ${JSON.stringify(branding, null, 2)} as const;
`;
fs.writeFileSync('src/environments/branding.ts', brandingContent);
fs.writeFileSync('desktop-app/src/branding.ts', brandingContent);
console.log(`Generated version: ${version}`);
console.log(`Generated branding profile: ${brandingProfile}`);
